version: '3.8'

services:
  nocodb:
    image: ${NOCODB_IMAGE}
    container_name: ${NOCODB_CONTAINER_NAME}
    restart: always
    networks:
      - ${TRAEFIK_NETWORK}
    volumes:
      - ./nocodb-data:/usr/app/data
    environment:
      - NC_AUTH_JWT_SECRET=${NOCODB_JWT_SECRET}
      - NC_PUBLIC_URL=${NOCODB_PUBLIC_URL}
      - NC_DISABLE_TELEMETRY=${NOCODB_DISABLE_TELEMETRY}
    deploy:
      resources:
        limits:
          cpus: '${NOCODB_CPUS_LIMIT}'
          memory: ${NOCODB_MEMORY_LIMIT}
        reservations:
          cpus: '${NOCODB_CPUS_RESERVATION}'
          memory: ${NOCODB_MEMORY_RESERVATION}
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"
      - "traefik.http.routers.nocodb.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.nocodb.entrypoints=${TRAEFIK_ENTRYPOINT}"
      - "traefik.http.routers.nocodb.tls.certresolver=${TRAEFIK_CERT_RESOLVER}"
      - "traefik.http.services.nocodb.loadbalancer.server.port=${TRAEFIK_INTERNAL_PORT}"

networks:
  nocodb:
    external: true
